name: trader_app
description: Trader app for interview
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  built_collection: ^5.1.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dio_http2_adapter: ^2.5.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  hooks_riverpod: ^2.5.4
  intl: any
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.5.3
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  retrofit_generator: ^9.1.3
  riverpod_generator: ^2.4.2
  riverpod_lint: any
  very_good_analysis: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
